sudo: required
services: 
  - docker

before_install:
  - docker build -t eschieffer/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true eschieffer/docker-react npm run test
 
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-522081385673"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  
